import { OperationFeedback } from "@/components/operation-feedback";
import Link from "next/link";
import { DeleteRecordItem } from "@/components/delete-record-item";
import { ListFilters } from "@/components/list-filters";
import { activeFilter, } from "@/lib/list-presentation";
import { Checkbox } from "@/components/ui/checkbox";
import { ServiceOnlineSettings } from "@/components/service-online-settings";
import { Clock, MoreHorizontal, Plus, Wrench } from "lucide-react";
import { createService, toggleService } from "@/app/actions/services";
import { EmptyState } from "@/components/empty-state"; import { PageHeader } from "@/components/page-header"; import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button"; import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"; import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"; import { Textarea } from "@/components/ui/textarea";
import { requireBarbershopAccess } from "@/lib/auth"; import { prisma } from "@/lib/prisma";
type BarberOption = { id: string; name: string };
type ServiceData = { publicImageUrl: string | null; barberServices: { barberId: string }[]; id: string; name: string; description: string | null; durationMinutes: number; price: { toString(): string }; isActive: boolean; isOnlineBookingEnabled: boolean; onlinePaymentPolicy: "NONE" | "OPTIONAL" | "FULL" | "DEPOSIT"; depositAmount: { toString(): string } | null };
const money = new Intl.NumberFormat("es-CL", { style: "currency", currency: "CLP", maximumFractionDigits: 0 });
export default async function ServicesPage({ searchParams }: { searchParams: Promise<{ error?: string; q?: string; status?: string }> }) { const membership = await requireBarbershopAccess(); const { error, q = "", status = "all" } = await searchParams; const [services, barbers] = await Promise.all([prisma.service.findMany({ where: { barbershopId: membership.barbershopId, ...activeFilter(status), name: { contains: q.trim(), mode: "insensitive" } }, include: { barberServices: { select: { barberId: true } } }, orderBy: { name: "asc" } }), prisma.barber.findMany({ where: { barbershopId: membership.barbershopId, isActive: true }, select: { id: true, name: true }, orderBy: { name: "asc" } })]); const owner = membership.role === "OWNER"; const create = <ServiceDialog barbers={barbers} action={createService} trigger={<><Plus />Nuevo servicio</>} />; return <section className="space-y-6"><PageHeader title="Servicios" description="Administra los servicios ofrecidos por tu barbería." action={owner ? create : undefined} /><OperationFeedback error={error} /><ListFilters q={q} status={status} placeholder="Buscar servicios..." />{services.length === 0 ? <EmptyState icon={<Wrench />} title="No se encontraron servicios." description="Prueba otra búsqueda o cambia el estado seleccionado." action={owner ? create : undefined} /> : <div className="overflow-hidden rounded-xl border bg-card"><Table><TableHeader><TableRow><TableHead>Servicio</TableHead><TableHead>Duración</TableHead><TableHead>Precio</TableHead><TableHead>Estado</TableHead><TableHead className="w-12" /></TableRow></TableHeader><TableBody>{services.map((service) => <TableRow key={service.id}><TableCell><Link href={`/services/${service.id}`} className="font-medium hover:underline">{service.name}</Link><div className="text-xs text-muted-foreground">{service.description || "Sin descripción"}</div></TableCell><TableCell><span className="inline-flex items-center gap-1.5"><Clock className="size-4 text-muted-foreground" />{service.durationMinutes} min</span></TableCell><TableCell>{money.format(Number(service.price))}</TableCell><TableCell><StatusBadge active={service.isActive} /></TableCell><TableCell>{owner && <ServiceActions service={service} />}</TableCell></TableRow>)}</TableBody></Table></div>}</section>; }
function ServiceDialog({ action, trigger, barbers }: { barbers: BarberOption[]; action: (data: FormData) => Promise<void>; trigger: React.ReactNode }) { return <Dialog><DialogTrigger nativeButton render={<Button nativeButton variant="default" />}>{trigger}</DialogTrigger><DialogContent className="max-h-[calc(100dvh-2rem)] overflow-y-auto"><ServiceForm barbers={barbers} action={action} /></DialogContent></Dialog>; }
function ServiceForm({ action, barbers }: { barbers: BarberOption[]; action: (data: FormData) => Promise<void> }) { return <form action={action}><DialogHeader><DialogTitle>Nuevo servicio</DialogTitle><DialogDescription>Define la duración y el precio del servicio.</DialogDescription></DialogHeader><div className="grid gap-4 py-5"><input type="hidden" name="id" value={""} /><input type="hidden" name="isActive" value="true" /><Field label="Nombre"><Input name="name" required defaultValue={""} /></Field><Field label="Descripción"><Textarea name="description" defaultValue={""} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Duración (minutos)"><Input name="durationMinutes" type="number" min="1" required defaultValue={""} /></Field><Field label="Precio CLP"><Input name="price" type="number" min="0" required defaultValue={""} /></Field></div><fieldset className="space-y-3"><legend className="text-sm font-medium">Profesionales</legend><p className="text-xs text-muted-foreground">Selecciona quiénes pueden realizar este servicio.</p>{barbers.length ? barbers.map(barber => <label key={barber.id} className="flex items-center gap-2 text-sm"><Checkbox name="barberIds" value={barber.id} defaultChecked />{barber.name}</label>) : <p className="text-sm text-muted-foreground">No hay profesionales activos. Puedes guardar el servicio sin habilitar la reserva online.</p>}</fieldset><ServiceOnlineSettings /></div><DialogFooter><DialogClose nativeButton render={<Button nativeButton type="button" variant="outline" />}>Cancelar</DialogClose><Button type="submit">Guardar servicio</Button></DialogFooter></form>; }
function ServiceActions({ service }: { service: ServiceData }) { return <DropdownMenu><DropdownMenuTrigger nativeButton render={<Button nativeButton variant="ghost" size="icon-sm" />}><MoreHorizontal /><span className="sr-only">Acciones</span></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem render={<Link href={`/services/${service.id}`} />}>Ver servicio</DropdownMenuItem><form action={toggleService}><input type="hidden" name="id" value={service.id} /><input type="hidden" name="isActive" value={String(!service.isActive)} /><DropdownMenuItem nativeButton render={<button type="submit" className="w-full" />}>{service.isActive ? "Desactivar" : "Activar"}</DropdownMenuItem></form><DeleteRecordItem kind="service" id={service.id} name={service.name} /></DropdownMenuContent></DropdownMenu>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="grid gap-2"><Label>{label}</Label>{children}</div>; }
