import { Clock, MoreHorizontal, Plus, Search, Wrench } from "lucide-react";
import { createService, toggleService, updateService } from "@/app/actions/services";
import { EmptyState } from "@/components/empty-state"; import { PageHeader } from "@/components/page-header"; import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button"; import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"; import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"; import { Textarea } from "@/components/ui/textarea";
import { requireBarbershopAccess } from "@/lib/auth"; import { prisma } from "@/lib/prisma";
type ServiceData = { id: string; name: string; description: string | null; durationMinutes: number; price: { toString(): string }; isActive: boolean };
const money = new Intl.NumberFormat("es-CL", { style: "currency", currency: "CLP", maximumFractionDigits: 0 });
export default async function ServicesPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) { const membership = await requireBarbershopAccess(); const services = await prisma.service.findMany({ where: { barbershopId: membership.barbershopId }, orderBy: { name: "asc" } }); const { error } = await searchParams; const owner = membership.role === "OWNER"; const create = <ServiceDialog action={createService} trigger={<><Plus />Nuevo servicio</>} />; return <section className="space-y-6"><PageHeader title="Servicios" description="Administra los servicios ofrecidos por tu barbería." action={owner ? create : undefined} />{error && <p className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<div className="flex items-center justify-between"><div className="relative w-full sm:max-w-sm"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input placeholder="Buscar servicios..." className="pl-9" /></div><Button variant="outline" disabled>Estado</Button></div>{services.length === 0 ? <EmptyState icon={<Wrench />} title="Aún no hay servicios" description="Crea el primer servicio de tu catálogo." action={owner ? create : undefined} /> : <div className="overflow-hidden rounded-xl border bg-card"><Table><TableHeader><TableRow><TableHead>Servicio</TableHead><TableHead>Duración</TableHead><TableHead>Precio</TableHead><TableHead>Estado</TableHead><TableHead className="w-12" /></TableRow></TableHeader><TableBody>{services.map((service) => <TableRow key={service.id}><TableCell><div className="font-medium">{service.name}</div><div className="text-xs text-muted-foreground">{service.description || "Sin descripción"}</div></TableCell><TableCell><span className="inline-flex items-center gap-1.5"><Clock className="size-4 text-muted-foreground" />{service.durationMinutes} min</span></TableCell><TableCell>{money.format(Number(service.price))}</TableCell><TableCell><StatusBadge active={service.isActive} /></TableCell><TableCell>{owner && <ServiceActions service={service} />}</TableCell></TableRow>)}</TableBody></Table></div>}</section>; }
function ServiceDialog({ action, service, trigger }: { action: (data: FormData) => Promise<void>; service?: ServiceData; trigger: React.ReactNode }) { return <Dialog><DialogTrigger nativeButton render={<Button nativeButton variant={service ? "ghost" : "default"} />}>{trigger}</DialogTrigger><DialogContent><ServiceForm action={action} service={service} /></DialogContent></Dialog>; }
function ServiceForm({ action, service }: { action: (data: FormData) => Promise<void>; service?: ServiceData }) { return <form action={action}><DialogHeader><DialogTitle>{service ? "Editar servicio" : "Nuevo servicio"}</DialogTitle><DialogDescription>Define la duración y el precio del servicio.</DialogDescription></DialogHeader><div className="grid gap-4 py-5"><input type="hidden" name="id" value={service?.id ?? ""} /><input type="hidden" name="isActive" value={String(service?.isActive ?? true)} /><Field label="Nombre"><Input name="name" required defaultValue={service?.name ?? ""} /></Field><Field label="Descripción"><Textarea name="description" defaultValue={service?.description ?? ""} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Duración (minutos)"><Input name="durationMinutes" type="number" min="1" required defaultValue={service?.durationMinutes ?? ""} /></Field><Field label="Precio CLP"><Input name="price" type="number" min="0" required defaultValue={service?.price.toString() ?? ""} /></Field></div></div><DialogFooter><DialogClose nativeButton render={<Button nativeButton type="button" variant="outline" />}>Cancelar</DialogClose><Button type="submit">Guardar servicio</Button></DialogFooter></form>; }
function ServiceActions({ service }: { service: ServiceData }) { return <Dialog><DropdownMenu><DropdownMenuTrigger nativeButton render={<Button nativeButton variant="ghost" size="icon-sm" />}><MoreHorizontal /></DropdownMenuTrigger><DropdownMenuContent align="end"><DialogTrigger nativeButton={false} render={<DropdownMenuItem />}>Editar</DialogTrigger><form action={toggleService}><input type="hidden" name="id" value={service.id} /><input type="hidden" name="isActive" value={String(!service.isActive)} /><DropdownMenuItem nativeButton render={<button type="submit" className="w-full" />}>{service.isActive ? "Desactivar" : "Activar"}</DropdownMenuItem></form></DropdownMenuContent></DropdownMenu><DialogContent><ServiceForm action={updateService} service={service} /></DialogContent></Dialog>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="grid gap-2"><Label>{label}</Label>{children}</div>; }
