import "dotenv/config";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { PrismaClient } from "@prisma/client";
import twilio from "twilio";
import { readNotificationConfig, type TwilioConfig } from "../src/lib/notifications/config";
import { MockNotificationSender, TwilioWhatsAppSender, renderMockReminder, templateVariables, resolveNotificationSender, type TwilioPayload } from "../src/lib/notifications/senders";
import { NotificationError, type ReminderSendInput, type NotificationSender } from "../src/lib/notifications/types";
import { processDueReminders } from "../src/lib/notifications/processor";
import { applyTwilioCallback, handleTwilioStatus } from "../src/lib/notifications/webhook";
import { handleReminderCron } from "../src/lib/notifications/cron";
import { reminderEvent, redactManageUrl } from "../src/lib/notifications/logging";
import { allowAppointmentAction } from "../src/lib/notifications/public-rate-limit";
import { issueAppointmentAccess } from "../src/lib/appointment-reminders";

const db = new PrismaClient();
const tenant = `provider-test-${randomUUID()}`;
const now = new Date("2031-01-02T12:00:00Z");
const config = readNotificationConfig({ NODE_ENV: "test", NOTIFICATION_PROVIDER: "mock" });
const twilioEnv = { NODE_ENV: "test", NOTIFICATION_PROVIDER: "twilio", REMINDER_PUBLIC_BASE_URL: "https://booking.example.test", TWILIO_ACCOUNT_SID: `AC${"a".repeat(32)}`, TWILIO_AUTH_TOKEN: "b".repeat(32), TWILIO_WHATSAPP_FROM: "whatsapp:+56911111111", TWILIO_TEMPLATE_FIRST_REMINDER: `HX${"c".repeat(32)}`, TWILIO_TEMPLATE_FINAL_REMINDER: `HX${"d".repeat(32)}` };
const twilioConfig = readNotificationConfig(twilioEnv).twilio!;
const sid = `SM${"e".repeat(32)}`;
const mock = new MockNotificationSender();
let checks = 0;
function pass(label: string) { console.log(`PASS ${++checks}: ${label}`); }
async function main() {
  assert.ok(["localhost", "127.0.0.1", "[::1]"].includes(new URL(process.env.DATABASE_URL!).hostname));
  const logs: string[] = [];
  const originalInfo = console.info;
  console.info = (...args: unknown[]) => { logs.push(args.map(String).join(" ")); };
  try {
    assert.equal(readNotificationConfig({ NODE_ENV: "development" }).provider, "mock");
    assert.throws(() => readNotificationConfig({ NODE_ENV: "production" }), /NOTIFICATION_PROVIDER/);
    assert.throws(() => readNotificationConfig({ NOTIFICATION_PROVIDER: "twilio", REMINDER_PUBLIC_BASE_URL: "https://example.test" }), /TWILIO_ACCOUNT_SID/);
    assert.equal(resolveNotificationSender(config).provider, "mock");
    pass("central config, explicit production provider and no credential fallback");
    const input: ReminderSendInput = { idempotencyKey: "test-reminder", attemptKey: randomUUID(), phone: "+56922222222", type: "FIRST_REMINDER", data: { barbershopName: "LUX test", customerName: "Cliente ficticio", barberName: "Barbero ficticio", serviceName: "Corte", localDate: "2031-01-03", localStartTime: "09:00", manageUrl: `https://booking.example.test/book/lux/manage/${"q".repeat(43)}` } };
    const payloads: TwilioPayload[] = [];
    const adapter = new TwilioWhatsAppSender(twilioConfig, async payload => { payloads.push(payload); return { sid }; });
    assert.equal((await adapter.sendReminder(input)).externalMessageId, sid);
    assert.equal(payloads[0].from, twilioEnv.TWILIO_WHATSAPP_FROM);
    assert.equal(payloads[0].to, "whatsapp:+56922222222");
    assert.equal(payloads[0].contentSid, twilioEnv.TWILIO_TEMPLATE_FIRST_REMINDER);
    assert.deepEqual(JSON.parse(payloads[0].contentVariables), templateVariables(input));
    assert.equal(new URL(payloads[0].statusCallback).searchParams.get("attempt"), input.attemptKey);
    assert.equal(new URL(payloads[0].statusCallback).pathname, "/api/webhooks/twilio/whatsapp/status");
    await adapter.sendReminder({ ...input, type: "FINAL_REMINDER" });
    assert.equal(payloads[1].contentSid, twilioEnv.TWILIO_TEMPLATE_FINAL_REMINDER);
    assert.ok(renderMockReminder(input).includes(input.data.manageUrl));
    assert.ok(renderMockReminder({ ...input, type: "FINAL_REMINDER" }).includes("próxima"));
    assert.equal((await mock.sendReminder(input)).externalMessageId, "mock:test-reminder");
    for (const [status, code] of [[429, "RATE_LIMIT"], [500, "PROVIDER_5XX"], [401, "INVALID_CREDENTIALS"], [400, "PROVIDER_REJECTED"]] as const) {
      const bad = new TwilioWhatsAppSender(twilioConfig, async () => { throw { status, message: `${twilioConfig.authToken} ${input.phone} ${input.data.manageUrl}` }; });
      await assert.rejects(bad.sendReminder(input), (error: unknown) => error instanceof NotificationError && error.code === code && !error.message.includes(twilioConfig.authToken));
    }
    await assert.rejects(adapter.sendReminder({ ...input, phone: "bad" }), /INVALID_PHONE/);
    pass("Twilio adapter/templates/SID/error classification with mocked transport, no internet");
    await db.barbershop.create({ data: { id: tenant, slug: tenant, name: "Provider test" } });
    const barber = await db.barber.create({ data: { barbershopId: tenant, name: "Barbero" } });
    const customer = await db.customer.create({ data: { barbershopId: tenant, name: "Cliente", phone: input.phone } });
    const service = await db.service.create({ data: { barbershopId: tenant, name: "Corte", durationMinutes: 30, price: 10000 } });
    const make = async () => {
      const a = await db.appointment.create({ data: { barbershopId: tenant, barberId: barber.id, customerId: customer.id, serviceId: service.id, startsAt: new Date(+now + 86400_000), endsAt: new Date(+now + 88200_000), price: 10000 } });
      return db.appointmentReminder.create({ data: { barbershopId: tenant, appointmentId: a.id, revision: 0, type: "FIRST_REMINDER", scheduledFor: now } });
    };
    const get = (id: string) => db.appointmentReminder.findUniqueOrThrow({ where: { id } });
    const run = (sender: NotificationSender = mock, time = now) => processDueReminders(db, { sender, now: time, config, barbershopId: tenant });
    let calls = 0;
    const counting: NotificationSender = { provider: "mock", async sendReminder(i) { calls++; return mock.sendReminder(i); } };
    const first = await make();
    await Promise.all([run(counting), run(counting)]);
    await run(counting);
    assert.equal(calls, 1); assert.equal((await get(first.id)).attemptCount, 1); assert.equal((await get(first.id)).status, "SENT");
    pass("mock due + concurrent processors + duplicate execution: one send");
    const retry = await make(); let retries = 0;
    const transient: NotificationSender = { provider: "mock", async sendReminder(i) { if (++retries < 3) throw new NotificationError("RATE_LIMIT", true); return mock.sendReminder(i); } };
    await run(transient);
    assert.equal((await get(retry.id)).status, "SCHEDULED");
    await run(transient); assert.equal(retries, 1);
    await run(transient, new Date(+now + 60_000));
    await run(transient, new Date(+now + 180_000));
    assert.equal((await get(retry.id)).status, "SENT"); assert.equal((await get(retry.id)).attemptCount, 3);
    pass("bounded exponential retry: fails twice, succeeds on third, respects backoff");
    const permanent = await make();
    await run({ provider: "mock", async sendReminder() { throw new NotificationError("INVALID_TEMPLATE"); } });
    await run(); assert.equal((await get(permanent.id)).status, "FAILED"); assert.equal((await get(permanent.id)).attemptCount, 1);
    const exhausted = await make();
    const alwaysFails: NotificationSender = { provider: "mock", async sendReminder() { throw new NotificationError("RATE_LIMIT", true); } };
    for (const delay of [0, 60_000, 180_000, 600_000]) await run(alwaysFails, new Date(+now + delay));
    assert.equal((await get(exhausted.id)).attemptCount, 3); assert.equal((await get(exhausted.id)).status, "FAILED");
    pass("permanent failure and maximum attempts never loop");
    const stale = await make(); const recent = await make();
    await db.appointmentReminder.update({ where: { id: stale.id }, data: { status: "PROCESSING", provider: "mock", processingStartedAt: new Date(+now - 600_000), attemptCount: 1, claimToken: randomUUID() } });
    await db.appointmentReminder.update({ where: { id: recent.id }, data: { status: "PROCESSING", provider: "mock", processingStartedAt: now, attemptCount: 1, claimToken: randomUUID() } });
    await run();
    assert.equal((await get(stale.id)).status, "SENT"); assert.equal((await get(stale.id)).attemptCount, 2);
    assert.equal((await get(recent.id)).status, "PROCESSING");
    await db.appointmentReminder.update({ where: { id: recent.id }, data: { status: "CANCELLED" } });
    pass("stale PROCESSING recovery; fresh lease is not stolen");
    const uncertain = await make();
    await db.appointmentReminder.update({ where: { id: uncertain.id }, data: { status: "PROCESSING", provider: "twilio", processingStartedAt: new Date(+now - 600_000), dispatchStartedAt: new Date(+now - 590_000), attemptCount: 1, claimToken: randomUUID() } });
    await run(); assert.equal((await get(uncertain.id)).status, "FAILED"); assert.equal((await get(uncertain.id)).lastError, "OUTCOME_UNKNOWN");
    const network = await make();
    await run({ provider: "twilio", async sendReminder() { throw new NotificationError("PROVIDER_5XX", true, true); } });
    assert.equal((await get(network.id)).status, "FAILED"); assert.equal((await get(network.id)).attemptCount, 1);
    pass("ambiguous Twilio send quarantined instead of risking duplicate WhatsApp");
    // Crash safety: token hash exists before sendReminder is entered.
    const durable = await make();
    await run({ provider: "mock", async sendReminder(i) {
      assert.ok(await db.appointmentPublicAccess.count({ where: { appointmentId: durable.appointmentId } }));
      return mock.sendReminder(i);
    } });
    pass("public link committed before external send");
    const callbackRow = await make(); const attemptKey = randomUUID();
    await db.appointmentReminder.update({ where: { id: callbackRow.id }, data: { provider: "twilio", status: "PROCESSING", claimToken: attemptKey, processingStartedAt: now, dispatchStartedAt: now } });
    async function callback(status: string, signatureValid = true, messageSid = sid, callbackConfig: TwilioConfig = twilioConfig) {
      const url = `${callbackConfig.callbackUrl}?reminder=${callbackRow.id}&attempt=${attemptKey}`;
      const params = { MessageSid: messageSid, MessageStatus: status, AccountSid: callbackConfig.accountSid, ExtraFutureField: "supported" };
      const signature = signatureValid ? twilio.getExpectedTwilioSignature(callbackConfig.authToken, url, params) : "invalid";
      // Internal proxy URL differs from external canonical origin.
      return handleTwilioStatus(new Request(`http://internal.local/api/webhooks/twilio/whatsapp/status${new URL(url).search}`, { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded", "x-twilio-signature": signature }, body: new URLSearchParams(params) }), db, callbackConfig);
    }
    assert.equal((await callback("delivered", false)).status, 403);
    assert.equal((await get(callbackRow.id)).externalMessageId, null);
    assert.equal((await callback("delivered")).status, 204);
    assert.equal((await get(callbackRow.id)).externalMessageId, sid);
    assert.equal((await get(callbackRow.id)).deliveryStatus, "DELIVERED");
    const stamp = (await get(callbackRow.id)).updatedAt.toISOString();
    await callback("delivered"); assert.equal((await get(callbackRow.id)).updatedAt.toISOString(), stamp);
    await callback("sent"); assert.equal((await get(callbackRow.id)).deliveryStatus, "DELIVERED");
    await callback("read"); assert.equal((await get(callbackRow.id)).deliveryStatus, "READ");
    await callback("failed"); assert.equal((await get(callbackRow.id)).deliveryStatus, "READ");
    assert.equal((await callback("delivered", true, `SM${"f".repeat(32)}`)).status, 204);
    assert.equal((await db.appointment.findUniqueOrThrow({ where: { id: callbackRow.appointmentId } })).status, "SCHEDULED");
    pass("signed callback, proxy URL, early SID race, duplicate/out-of-order, unknown SID, no Appointment mutation");
    const deliveryFailure = await make();
    const failureSid = `SM${"1".repeat(32)}`;
    await db.appointmentReminder.update({ where: { id: deliveryFailure.id }, data: { status: "SENT", provider: "twilio", externalMessageId: failureSid, deliveryStatus: "QUEUED" } });
    await applyTwilioCallback(db, { sid: failureSid, status: "undelivered" });
    assert.equal((await get(deliveryFailure.id)).deliveryStatus, "UNDELIVERED");
    assert.equal((await get(deliveryFailure.id)).status, "SENT");
    assert.equal((await db.appointment.findUniqueOrThrow({ where: { id: deliveryFailure.appointmentId } })).status, "SCHEDULED");
    await db.appointmentReminder.update({ where: { id: deliveryFailure.id }, data: { status: "CANCELLED" } });
    await applyTwilioCallback(db, { sid: failureSid, status: "delivered" });
    assert.equal((await get(deliveryFailure.id)).status, "CANCELLED");
    pass("delivery failure preserves Appointment and late callbacks preserve cancellation");
    const access = await db.$transaction(tx => issueAppointmentAccess(tx, tenant, callbackRow.appointmentId, now));
    const token = access.split("/").at(-1)!;
    const attempts = await Promise.all(Array.from({ length: 15 }, () => allowAppointmentAction(db, token, now)));
    assert.equal(attempts.filter(Boolean).length, 10);
    assert.equal(await allowAppointmentAction(db, token, new Date(+now + 60_001)), true);
    assert.equal(await allowAppointmentAction(db, "not-valid", now), false);
    pass("shared PostgreSQL action limit is atomic across concurrent requests");
    let executions = 0; const cronSecret = "s".repeat(40);
    const runner = async () => { executions++; return { sent: 1, failed: 0 }; };
    const request = (secret?: string) => new Request("http://localhost/api/internal/reminders/process", { headers: secret ? { authorization: `Bearer ${secret}` } : {} });
    assert.equal((await handleReminderCron(request(), cronSecret, runner)).status, 401);
    assert.equal((await handleReminderCron(request("wrong"), cronSecret, runner)).status, 401);
    assert.equal((await handleReminderCron(request(cronSecret), undefined, runner)).status, 401);
    assert.equal((await handleReminderCron(request(cronSecret), cronSecret, runner)).status, 200);
    assert.equal(executions, 1);
    pass("cron authentication: missing/wrong/unconfigured rejected, correct executes once");
    reminderEvent("reminder_sent", { reminderId: first.id, ...({ secret: twilioConfig.authToken, phone: input.phone, manageUrl: input.data.manageUrl } as object) });
    const output = logs.join("\n");
    for (const secret of [token, input.phone, input.data.manageUrl, twilioConfig.authToken]) assert.ok(!output.includes(secret));
    assert.ok(redactManageUrl(input.data.manageUrl).endsWith("/manage/[REDACTED]"));
    for (const event of ["reminder_claimed", "reminder_sent", "reminder_failed", "reminder_recovered", "twilio_callback"]) assert.ok(output.includes(event));
    pass("structured logs allow only internal IDs; no phone, action token, URL or auth token");
    console.log(`All ${checks} provider checks passed (no Twilio network calls).`);
  } finally {
    console.info = originalInfo;
    const where = { barbershopId: tenant };
    await db.appointmentPublicAccess.deleteMany({ where }); await db.appointmentReminder.deleteMany({ where }); await db.appointment.deleteMany({ where });
    await db.customer.deleteMany({ where }); await db.service.deleteMany({ where }); await db.barber.deleteMany({ where }); await db.barbershop.deleteMany({ where: { id: tenant } });
    await db.$disconnect();
  }
}
main().catch(error => { console.error(error instanceof Error ? error.message : "Provider test failed"); process.exitCode = 1; });
