import Link from "next/link";
import { MoreHorizontal, Plus, Scissors, Search } from "lucide-react";
import { createBarber, toggleBarber, updateBarber } from "@/app/actions/barbers";
import { EmptyState } from "@/components/empty-state";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { requireBarbershopAccess } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

type BarberData = { id: string; name: string; phone: string | null; email: string | null; commissionRate: { toString(): string }; isActive: boolean };

export default async function BarbersPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const membership = await requireBarbershopAccess(); const { error } = await searchParams; const owner = membership.role === "OWNER";
  const barbers = await prisma.barber.findMany({ where: { barbershopId: membership.barbershopId }, orderBy: { name: "asc" } });
  const create = <BarberDialog action={createBarber} trigger={<><Plus />Nuevo barbero</>} />;
  return <section className="space-y-6"><PageHeader title="Barberos" description="Administra el equipo de tu barbería." action={owner ? create : undefined} />{error && <p className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<div className="flex items-center justify-between"><div className="relative w-full sm:max-w-sm"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input placeholder="Buscar barberos..." className="pl-9" /></div><Button variant="outline" disabled>Estado</Button></div>{barbers.length === 0 ? <EmptyState icon={<Scissors />} title="Aún no hay barberos" description="Agrega integrantes a tu equipo." action={owner ? create : undefined} /> : <div className="overflow-hidden rounded-xl border bg-card"><Table><TableHeader><TableRow><TableHead>Barbero</TableHead><TableHead>Contacto</TableHead><TableHead>Comisión</TableHead><TableHead>Estado</TableHead><TableHead className="w-12" /></TableRow></TableHeader><TableBody>{barbers.map((barber) => <TableRow key={barber.id}><TableCell className="font-medium"><Link className="hover:underline" href={`/barbers/${barber.id}`}>{barber.name}</Link></TableCell><TableCell className="text-muted-foreground">{barber.phone || barber.email || "—"}</TableCell><TableCell>{barber.commissionRate.toString()}%</TableCell><TableCell><StatusBadge active={barber.isActive} /></TableCell><TableCell>{owner && <BarberActions barber={barber} />}</TableCell></TableRow>)}</TableBody></Table></div>}</section>;
}

function BarberDialog({ action, barber, trigger }: { action: (data: FormData) => Promise<void>; barber?: BarberData; trigger: React.ReactNode }) { return <Dialog><DialogTrigger nativeButton render={<Button nativeButton variant={barber ? "ghost" : "default"} />}>{trigger}</DialogTrigger><DialogContent><BarberForm action={action} barber={barber} /></DialogContent></Dialog>; }
function BarberForm({ action, barber }: { action: (data: FormData) => Promise<void>; barber?: BarberData }) { return <form action={action}><DialogHeader><DialogTitle>{barber ? "Editar barbero" : "Nuevo barbero"}</DialogTitle><DialogDescription>Completa la información del barbero.</DialogDescription></DialogHeader><div className="grid gap-4 py-5"><input type="hidden" name="id" value={barber?.id ?? ""} /><input type="hidden" name="isActive" value={String(barber?.isActive ?? true)} /><Field label="Nombre"><Input name="name" required defaultValue={barber?.name ?? ""} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Teléfono"><Input name="phone" defaultValue={barber?.phone ?? ""} /></Field><Field label="Email"><Input name="email" type="email" defaultValue={barber?.email ?? ""} /></Field></div><Field label="Comisión (%)"><Input name="commissionRate" type="number" min="0" max="100" step="0.01" defaultValue={barber?.commissionRate.toString() ?? "0"} /></Field></div><DialogFooter><DialogClose nativeButton render={<Button nativeButton type="button" variant="outline" />}>Cancelar</DialogClose><Button type="submit">Guardar barbero</Button></DialogFooter></form>; }
function BarberActions({ barber }: { barber: BarberData }) { return <Dialog><DropdownMenu><DropdownMenuTrigger nativeButton render={<Button nativeButton variant="ghost" size="icon-sm" />}><MoreHorizontal /></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem nativeButton={false} render={<Link href={`/barbers/${barber.id}`} />}>Ver disponibilidad</DropdownMenuItem><DialogTrigger nativeButton={false} render={<DropdownMenuItem />}>Editar</DialogTrigger><form action={toggleBarber}><input type="hidden" name="id" value={barber.id} /><input type="hidden" name="isActive" value={String(!barber.isActive)} /><DropdownMenuItem nativeButton render={<button type="submit" className="w-full" />}>{barber.isActive ? "Desactivar" : "Activar"}</DropdownMenuItem></form></DropdownMenuContent></DropdownMenu><DialogContent><BarberForm action={updateBarber} barber={barber} /></DialogContent></Dialog>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="grid gap-2"><Label>{label}</Label>{children}</div>; }
