import { Button } from "@/components/ui/button";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

type CustomerData = { id: string; name: string; phone: string | null; email: string | null; notes: string | null; isActive: boolean };
export function CustomerDialog({ action, customer, trigger }: { action: (data: FormData) => Promise<void>; customer?: CustomerData; trigger: React.ReactNode }) { return <Dialog><DialogTrigger nativeButton render={<Button nativeButton variant={customer ? "ghost" : "default"} size={customer ? "sm" : "default"} />}>{trigger}</DialogTrigger><DialogContent className="sm:max-w-lg"><form action={action}><DialogHeader><DialogTitle>{customer ? "Editar cliente" : "Nuevo cliente"}</DialogTitle><DialogDescription>{customer ? "Actualiza la información del cliente." : "Agrega un cliente a tu barbería."}</DialogDescription></DialogHeader><div className="grid gap-4 py-5"><input type="hidden" name="id" value={customer?.id ?? ""} /><input type="hidden" name="isActive" value={String(customer?.isActive ?? true)} /><Field label="Nombre"><Input name="name" required defaultValue={customer?.name ?? ""} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Teléfono"><Input name="phone" defaultValue={customer?.phone ?? ""} /></Field><Field label="Email"><Input name="email" type="email" defaultValue={customer?.email ?? ""} /></Field></div><Field label="Notas"><Textarea name="notes" defaultValue={customer?.notes ?? ""} rows={4} /></Field></div><DialogFooter><DialogClose nativeButton render={<Button nativeButton type="button" variant="outline" />}>Cancelar</DialogClose><Button type="submit">Guardar cliente</Button></DialogFooter></form></DialogContent></Dialog>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="grid gap-2"><Label>{label}</Label>{children}</div>; }
