import { MoreHorizontal, Plus, Search, Users } from "lucide-react";
import { createCustomer, toggleCustomer, updateCustomer } from "@/app/actions/customers";
import { EmptyState } from "@/components/empty-state";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { requireBarbershopAccess } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

type CustomerData = { id: string; name: string; phone: string | null; email: string | null; notes: string | null; isActive: boolean };
export default async function CustomersPage({ searchParams }: { searchParams: Promise<{ error?: string; q?: string }> }) { const membership = await requireBarbershopAccess(); const { error, q = "" } = await searchParams; const customers = await prisma.customer.findMany({ where: { barbershopId: membership.barbershopId, name: { contains: q, mode: "insensitive" } }, orderBy: { name: "asc" } }); const owner = membership.role === "OWNER"; const newDialog = <CustomerDialog action={createCustomer} trigger={<><Plus />Nuevo cliente</>} />; return <section className="space-y-6"><PageHeader title="Clientes" description="Gestiona la información y el estado de tus clientes." action={owner ? newDialog : undefined} />{error && <p className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><form className="relative w-full sm:max-w-sm"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input name="q" defaultValue={q} placeholder="Buscar clientes..." className="pl-9" /></form><Button variant="outline" disabled>Estado</Button></div>{customers.length === 0 ? <EmptyState icon={<Users />} title="Aún no hay clientes" description="Crea el primer cliente para comenzar a construir tu base." action={owner ? newDialog : undefined} /> : <div className="overflow-hidden rounded-xl border bg-card"><Table><TableHeader><TableRow><TableHead>Cliente</TableHead><TableHead>Contacto</TableHead><TableHead>Estado</TableHead><TableHead className="w-12" /></TableRow></TableHeader><TableBody>{customers.map((customer) => <TableRow key={customer.id}><TableCell className="font-medium">{customer.name}</TableCell><TableCell className="text-muted-foreground"><div>{customer.phone || "Sin teléfono"}</div><div className="text-xs">{customer.email || "Sin email"}</div></TableCell><TableCell><StatusBadge active={customer.isActive} /></TableCell><TableCell>{owner && <CustomerActions customer={customer} />}</TableCell></TableRow>)}</TableBody></Table></div>}</section>; }

function CustomerDialog({ action, customer, trigger }: { action: (data: FormData) => Promise<void>; customer?: CustomerData; trigger: React.ReactNode }) { return <Dialog><DialogTrigger nativeButton render={<Button nativeButton variant={customer ? "ghost" : "default"} size={customer ? "sm" : "default"} />}>{trigger}</DialogTrigger><DialogContent className="sm:max-w-lg"><form action={action}><DialogHeader><DialogTitle>{customer ? "Editar cliente" : "Nuevo cliente"}</DialogTitle><DialogDescription>{customer ? "Actualiza la información del cliente." : "Agrega un cliente a tu barbería."}</DialogDescription></DialogHeader><div className="grid gap-4 py-5"><input type="hidden" name="id" value={customer?.id ?? ""} /><input type="hidden" name="isActive" value={String(customer?.isActive ?? true)} /><Field label="Nombre"><Input name="name" required defaultValue={customer?.name ?? ""} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Teléfono"><Input name="phone" defaultValue={customer?.phone ?? ""} /></Field><Field label="Email"><Input name="email" type="email" defaultValue={customer?.email ?? ""} /></Field></div><Field label="Notas"><Textarea name="notes" defaultValue={customer?.notes ?? ""} rows={4} /></Field></div><DialogFooter><DialogClose nativeButton render={<Button nativeButton type="button" variant="outline" />}>Cancelar</DialogClose><Button type="submit">Guardar cliente</Button></DialogFooter></form></DialogContent></Dialog>; }
function CustomerActions({ customer }: { customer: CustomerData }) { return <Dialog><DropdownMenu><DropdownMenuTrigger nativeButton render={<Button nativeButton variant="ghost" size="icon-sm" />}><MoreHorizontal /><span className="sr-only">Acciones</span></DropdownMenuTrigger><DropdownMenuContent align="end"><DialogTrigger nativeButton={false} render={<DropdownMenuItem />}>Editar</DialogTrigger><form action={toggleCustomer}><input type="hidden" name="id" value={customer.id} /><input type="hidden" name="isActive" value={String(!customer.isActive)} /><DropdownMenuItem nativeButton render={<button type="submit" className="w-full" />}>{customer.isActive ? "Desactivar" : "Activar"}</DropdownMenuItem></form></DropdownMenuContent></DropdownMenu><DialogContent className="sm:max-w-lg"><form action={updateCustomer}><DialogHeader><DialogTitle>Editar cliente</DialogTitle><DialogDescription>Actualiza la información del cliente.</DialogDescription></DialogHeader><div className="grid gap-4 py-5"><input type="hidden" name="id" value={customer.id} /><input type="hidden" name="isActive" value={String(customer.isActive)} /><Field label="Nombre"><Input name="name" required defaultValue={customer.name} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Teléfono"><Input name="phone" defaultValue={customer.phone ?? ""} /></Field><Field label="Email"><Input name="email" type="email" defaultValue={customer.email ?? ""} /></Field></div><Field label="Notas"><Textarea name="notes" defaultValue={customer.notes ?? ""} rows={4} /></Field></div><DialogFooter><DialogClose nativeButton render={<Button nativeButton type="button" variant="outline" />}>Cancelar</DialogClose><Button type="submit">Guardar cambios</Button></DialogFooter></form></DialogContent></Dialog>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="grid gap-2"><Label>{label}</Label>{children}</div>; }
